[tool.poetry]
name = "talks"
version = "1.0.0"
description = ""
authors = ["Mark Lee"]

[tool.poetry.dependencies]
python = "^3.6"
hovercraft = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
